### ISSUE TITLE
Please improve directory structure

### ISSUE THREAD

**Issue by pcav** [gee-community/qgis-earthengine-plugin#29]
Probably better move files out of the plugin subdir. See other plugins as an example.

**Comment by gena** [comment]
Which files, you mean dependencies? They feel indeed a bit weird indeed. I was advised to use a plugin template developed by @volaya, which is based on Paver, e.g. https://github.com/planetfederal/qgis-tester-plugin. As far as I understood, it embeds all dependencies as a part of the plugin using ```paver package```. 
If there is a better example of a (multi-platform) plugin with multiple Python dependencies - I'd be more than happy to improve this. We had an option to install dependencies at the beginning, but it was causing some issues during the installation of some libraries, like pyCrypto.

**Comment by pcav** [comment]
I meant https://github.com/gee-community/qgis-earthengine-plugin/tree/master/ee_plugin
Which dependencies are you referring to? We strongly advise against including libraries in the plugin.

**Comment by gena** [comment]
Ah, yes, you mean like in https://github.com/pcav/GeodesicDensifier3 where ```__init__.py``` is at the main level? In my case, the https://github.com/gee-community/qgis-earthengine-plugin/tree/master/ee_plugin is the actual plugin directory deployed under QGIS. Probably that is what causes confusion. I've moved it into a separate directory because to keep things clean, the rest does not have to be installed together with the plugin, but is needed as supplementary materials (user guide, examples, etc.). Dependencies - I meant something like https://github.com/planetfederal/qgis-tester-plugin/blob/master/requirements.txt.

**Comment by pcav** [comment]
What are the files that should not go into the plugin?

**Comment by gena** [comment]
I've reorganized the structure by moving everything to the top-level as suggested, do you have any further suggestions? This is my first QGIS plugin.

**Comment by pcav** [comment]
Looks good to me.
Thanks.
